### ISSUE TITLE
Enabling chat while frozen

### ISSUE THREAD

**Issue by benjaramire3** [ZeTioZ/ZeFreeze#1]
Hello, how can I make it so that those who are with /freeze can write in the chat?

**Comment by ZeTioZ** [comment]
Hi, what do you get when you try to chat? I don't remember having muted the players from chatting while frozen.

**Comment by benjaramire3** [comment]
An annoying inventory appears that I cannot remove

**Comment by benjaramire3** [comment]
nothing nothing solved it

**Comment by ZeTioZ** [comment]
> nothing nothing solved it

You just have to disable the anti disconnection gui in the config file
